### PR TITLE
Fix path error when creating new project on Windows, see #101

### PR DESCRIPTION
**Pull request by aelayeb**

### CODE REVIEW

**Comment by aelayeb** [comment]
Maybe we need to add "path" package to dependencies in the pubspec ?

**Comment by joeconwaystk** [comment]
This works! 

re: Path - Yes, even though yaml depends on it, I think if we explicitly refer to functionality in path it should be in the pubspec. Looks like "^1.0.0" will work.

**Comment by joeconwaystk** [comment]
Once path is added to pubspec, I'll merge this into my branch and we'll get this deployed to pub shortly, with a few other fixes that have gone on.

**Comment by aelayeb** [comment]
Ok good !
One more thing : I was careless about naming the path import.
It'll be better if you can rename the "pathLib' occurences to "path_lib".
According to : https://www.dartlang.org/guides/language/effective-dart/style#do-name-import-prefixes-using-lowercasewithunderscores

**Pull request merged**
