### PR TITLE
Adds SIGINT handler to shut down app gracefully

### PR DESCRIPTION
**Pull request by joeconwaystk**

### CODE REVIEW

**Comment by MarcusSmith** [comment]
Is there a way to force a SIGINT in a unit test to ensure that it stops the app and throws the correct exception?

**Comment by joeconwaystk** [comment]
I think technically just invoking the interrupt handler would do it, but I don't want to make it part of the public API. I'll think on that some, tho.

**Comment by anachlas** [comment]
Something in `isolate_failure_test.dart` keeps hanging on Travis

**Comment by joeconwaystk** [comment]
Yeah those tests are the ones that stall sometimes on travis will re run

**Pull request merged**
