### PR TITLE
API reference documentation and some name changes

### PR DESCRIPTION
**Pull request by joeconwaystk**
Sorry for the size. Changed a lot of names to make the API more discoverable. Adding documentation for aqueduct classes and methods. This branch needs to be rebased after #91 is merged.

### CODE REVIEW

**Comment by smswz** [comment]
Are there any non-name changes? Github chokes on this diff

**Comment by joeconwaystk** [comment]
Well, name changes and API docs. If you checkout this branch and run dartdoc, then open doc/api/index.html, you'll see the full breadth of the changes

**Comment by smswz** [comment]
👍  from me

**Comment by anachlas** [comment]
The only one I'm not sure about is `OrderedSet` -> `ManagedSet`.  Thoughts?

**Comment by joeconwaystk** [comment]
Really? Why? That was the one I was most sure of. Not saying I'm right, but interested as to why

**Comment by anachlas** [comment]
Well set implies to me an unordered collection, but it looks like it would preserve order.

**Comment by anachlas** [comment]
Also set implies uniqueness which isn't necessary here.

**Comment by anachlas** [comment]
Well actually it is unique, but the ordered thing still bugs me.

**Comment by joeconwaystk** [comment]
Well it is unique, but also there is no order - it'll be in the order the database decides. It may even be a subset.

**Comment by anachlas** [comment]
Ok in that case I'm fine with it, 👍

**Pull request merged**
