### PR TITLE
Increase pub get timeout and let it fail

### LINKED ISSUE #292: Issues with tooling on windows 10
Hi

I just tried Dart for the first time.
I have 2 major issues which are stopping me from even starting out;

1.  When i try `pub global activate angel_cli`, the process gets stuck at `Installed executable angel.`.
I am assuming that Angel was indeed instaled but i am not sure if any further steps were not performed.

2. `aqueduct create` is timing out. I have tried it with different networks so it doesnt seems to be a network issue.

````
PS C:\Users\Mockingbird\DevSpace\Dart> aqueduct create testproj
-- Aqueduct CLI Version: 2.3.0
    Aqueduct directory is: C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0
    Template source is: C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\
    See more templates with 'aqueduct create list-templates'
-- Copying template files to new project directory (C:\Users\Mockingbird\DevSpace\Dart\testproj)...
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\.analysis_options
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\.gitignore
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\.travis.yml
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\bin
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\config.src.yaml
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\lib
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\pubspec.yaml
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\README.md
    Copying contents of C:\Users\Mockingbird\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\aqueduct-2.3.0\example\te
mplates\default\test
    Generating config.yaml from config.src.yaml.
-- Fetching project dependencies (pub get --no-packages-dir )...
*** Timed out fetching dependencies. Reconnect to the internet or use --offline.
*** TimeoutException after 0:00:20.000000: Future not completed
````

I am on windows 10, 64 bits and have installed Aqueduct version 2.3.0
Dart is `Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"`

### PR DESCRIPTION
**Pull request by joeconwaystk**
Fixes #292

### CODE REVIEW

**Comment by joeconwaystk** [comment]
i don't know why code coverage dropped his much so I have to check this, it seems weird

**Comment by MarcusSmith** [comment]
@joeconwaystk Does this PR need to be rebased off of what's currently on master? All the files that it mentions code coverage dropping look to be related to the `whereNot` PR, but there was coverage for those....

**Comment by joeconwaystk** [comment]
I think/hope so, I did re base so we'll find out when the checks run

**Comment by MarcusSmith** [comment]
The coverage looks correct now

**Pull request merged**
