### PR TITLE
Jc/scripts

### PR DESCRIPTION
**Pull request by joeconwaystk**
Some final details for scripts and read mes. Needs to be rebased.

### CODE REVIEW

**Comment by smswz** [comment]
Is this rebased?

**Comment by joeconwaystk** [comment]
Yes, it has been rebased

**Comment by anachlas** [comment]
Needs to be rebased again.

**Comment by joeconwaystk** [comment]
rebased

**Comment by anachlas** [comment]
Well one thing, I dont remember how to fix it but the github markdown numbering is broken for the readme

**Comment by anachlas** [comment]
👍 Looks good to me.

**Pull request merged**
