### PR TITLE
Expose ManagedRelationshipType

### PR DESCRIPTION
**Pull request by sudolibre**
ManagedRelationshipType is exposed via the relationshipType property on ManagedRelationshipDescription however the type itself is not exposed outside the package. This means that we cannot perform checks such as
`if (managedRelationshipDescription.relationshipType == ManagedRelationshipType.hasMany)`

This PR is to expose this type to enable such checks.

### CODE REVIEW

**Comment by joeconwaystk** [comment]
Can you import 'package:aqueduct/src/db/managed/relationship_type.dart' from your app without exporting this?

**Comment by sudolibre** [comment]
> Can you import 'package:aqueduct/src/db/managed/relationship_type.dart' from your app without exporting this?

I can but it causes this warning from the analysis server: ```Don't import implementation files from another package. (implementation_imports at [reservoir] lib/src/entity_controller.dart:5)```

**Comment by joeconwaystk** [comment]
Fair enough

**Comment by joeconwaystk** [comment]
Can you add documentation comments to the enum if it's going to be public facing?

**Comment by sudolibre** [comment]
> Can you add documentation comments to the enum if it's going to be public facing?
> 
> View changes

added the following comment: ```/// The possible database relationships.```

**Pull request merged**
